export const AUTHENTICATE = 'AUTHENTICATE ';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATE_ON_RELOAD = 'AUTHENTICATE_ON_RELOAD';

export const FETCH_POST = 'FETCH_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const RESET_POST_CONTENT = 'RESET_POST_CONTENT';
export const TOGGLE ='TOGGLE';
export const POST_COMMENT = 'POST_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
